version: "3.4"

services:
  ping_service:
    image: ping_service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SERVICE_NAME=ping_service
    ports:
      - 8000:8000

  pong_service:
    image: drfmicro
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SERVICE_NAME=pong_service
    ports:
      - 8001:8000

  pp_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "pp_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
